/*
SET sql_notes = 0;      -- Temporarily disable the "Table already exists" warning
CREATE TABLE IF NOT EXISTS ChatUsers(
    USER_NAME VARCHAR (255) NOT NULL,
    USER_PWD VARCHAR (255) NOT NULL,
    FIRST_NAME VARCHAR (255) NOT NULL,
    LAST_NAME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    PRIMARY KEY (USER_NAME (50))
);

CREATE TABLE IF NOT EXISTS UserProfile(
    USER_NAME VARCHAR (255),
    STATE VARCHAR (255),
    BIO VARCHAR (255),
    USER_PICTURE LONGBLOB,
    PRIMARY KEY (USER_NAME (50))
);



CREATE TABLE IF NOT EXISTS ChatChannel(
    CHANNEL_NAME VARCHAR (255) NOT NULL,
    PRIMARY KEY (CHANNEL_NAME (50))
);

/*
1 - USER
2 - MODERATOR
3 - ADMIN
*/

CREATE TABLE IF NOT EXISTS users_channels(
    ID BIGINT (11) NOT NULL AUTO_INCREMENT,
    CHANNEL_NAME VARCHAR (255) NOT NULL,
    USER_NAME VARCHAR (255) NOT NULL,
    USER_TYPE BIGINT (11) NOT NULL DEFAULT 1,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS messages(
    MSG_ID BIGINT (11) NOT NULL AUTO_INCREMENT,
    CHANNEL_NAME VARCHAR (255) NULL,
    USER_NAME VARCHAR (255) NULL,
    MSG_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MESSAGE VARCHAR (255) NOT NULL,
    MESSAGE_TYPE JSON NULL,
    PRIMARY KEY (MSG_ID)
);



-- O IS FALSE AND 1 IS TRUE IN MYSQL


SET sql_notes = 1;      -- And then re-enable the warning again


*/
